
// actions load data
export const SET_USER = 'SET_USER';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_COPY_HISTORY = 'SET_HISTORY';

//actions 
export const ORDER_PRICE = 'ORDER_PRICE';
export const FILTER_HIGHEST_PRICE = 'FILTER_HIGHEST_PRICE'
export const FILTER_CATEGORY_HOME = 'FILTER_CATEGORY_HOME';
export const FILTER_CATEGORY_HISTORY = 'FILTER_CATEGORY_HISTORY';
export const SET_ALL_PRODUCTS_HISTORY = 'SET_ALL_PRODUCTS_HISTORY';
export const SET_PAGE = 'SET_PAGE';
export const REDEEM_PRODUCT = 'REDEEM_PRODUCT';
export const RECENTS_PRODUCTS = 'RECENTS_PRODUCTS';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';